name: cd
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare java
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          lein: latest
      - name: Deploy clojar
        env:
          CLOJARS_USER: ${{ secrets.CLOJARS_USER }}
          CLOJARS_PASS: ${{ secrets.CLOJARS_PASS }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          export GPG_TTY=$(tty)
          lein deploy clojars
